/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package openweather_based_weather_client;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import openweather_based_weather_client.frmMain;
import org.json.JSONException;

/**
 *
 * @author pavlidis_aris
 */
public class frmKairosTwra extends javax.swing.JFrame {

    DefaultTableModel model;
    frmMain mainForm = new frmMain();
    
    /**
     * Creates new form frmKairosTwra
     */
    public frmKairosTwra() throws SQLException, JSONException {
        initComponents();
        model = new DefaultTableModel();
        jTable1.setModel(model);
        model.addColumn("Κωδικός πόλης");
        model.addColumn("Θερμοκρασία");
        model.addColumn("Περιγραφή καιρού");
        model.addColumn("Νεφοκάλυψη");
        model.addColumn("Ταχύτητα ανέμου");
        model.addColumn("Ημερομηνία - Ώρα");
        model.addColumn("Ύψος βροχής");
        model.addColumn("Ύψος χιονιού");        
        mainForm.EnimerwsiTrexontwsKairou("http://api.openweathermap.org/data/2.5/group?id=264371,734077,8133690,8133786,261743&units=metric&appid=fd798713a90f9501121e8dc78d7d0a47");
        mainForm.LoadTable("SELECT city_id, temperature, weather_description, clouds, wind_speed, dt, rain, snow FROM TBL_WEATHERDATA ORDER BY CITY_ID DESC");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnKairosTwra = new javax.swing.JMenu();
        mnAnanewsiKairou = new javax.swing.JMenu();
        mnEpistrofi = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        mnKairosTwra.setText("Καιρός τώρα");
        jMenuBar1.add(mnKairosTwra);

        mnAnanewsiKairou.setText("Ανανέωση καιρού");
        jMenuBar1.add(mnAnanewsiKairou);

        mnEpistrofi.setText("Επιστροφή");
        mnEpistrofi.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                mnEpistrofiMenuSelected(evt);
            }
        });
        jMenuBar1.add(mnEpistrofi);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 826, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnEpistrofiMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_mnEpistrofiMenuSelected
        // TODO add your handling code here:
        mainForm.setVisible(true);
        dispose();
    }//GEN-LAST:event_mnEpistrofiMenuSelected

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmKairosTwra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmKairosTwra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmKairosTwra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmKairosTwra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new frmKairosTwra().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(frmKairosTwra.class.getName()).log(Level.SEVERE, null, ex);
                } catch (JSONException ex) {
                    Logger.getLogger(frmKairosTwra.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenu mnAnanewsiKairou;
    private javax.swing.JMenu mnEpistrofi;
    private javax.swing.JMenu mnKairosTwra;
    // End of variables declaration//GEN-END:variables
}
